### ISSUE TITLE
Getting URLs of playlist fails

### ISSUE THREAD

**Issue by bennetrr** [tamland/python-tidal#103]
I want to get the urls of my playlist. The playlist contains 62 items. Here is the error:

```python
Traceback (most recent call last):
  File "D:\coding\weckpi\venv\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\benne\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\221.5787.24\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\benne\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\221.5787.24\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/coding/weckpi/weckpi-core/test_e2e/music/tidal_userpl_random.py", line 40, in <module>
    playlist = session.get_playable_data(synthpop_playlist)
  File "D:\coding\weckpi\weckpi-core\src\music\tidal\tidal_session.py", line 198, in get_playable_data
    output_list.append(track_to_pli(track))
  File "D:\coding\weckpi\weckpi-core\src\music\tidal\tidal_session.py", line 165, in track_to_playlist_item
    mrl = track.get_url()
  File "D:\coding\weckpi\venv\lib\site-packages\tidalapi\media.py", line 157, in get_url
    request = self.requests.request('GET', 'tracks/%s/urlpostpaywall' % self.id, params)
  File "D:\coding\weckpi\venv\lib\site-packages\tidalapi\request.py", line 85, in request
    request = self.basic_request(method, path, params, data, headers)
  File "D:\coding\weckpi\venv\lib\site-packages\tidalapi\request.py", line 63, in basic_request
    if not request.ok and request.json()['userMessage'].startswith("The token has expired.") and refresh_token:
  File "D:\coding\weckpi\venv\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
```

The code that I'm using is simplified the following:
```python
def get_playable_data(obj: tidalapi.Playlist):
    output_list = []

    for track in obj.tracks():
        if not track.available:
            raise FileNotFoundError(
                f'The track {track.name} by {track.artist.name} from {track.album.name} is not available')

        mrl = track.get_url()
        title = track.name
        artist = track.artist.name
        album = track.album.name
        try:
            cover = track.album.image(1280)
        except AttributeError:
            cover = None

        output_list.append((mrl, title, artist, album, cover))
        
    return output_list
```

The error occurs at the 59 item I think.

**Comment by bennetrr** [comment]
Addition: For another playlist the code works, but the playlist is about 3 times smaller. The function above also fails with large lists in general, like the top songs of artists

**Comment by morguldir** [comment]
Sounds like #106 could help

**Comment by bennetrr** [comment]
Thanks, I will try this in a few days.

Btw, do you plan to release the 0.7 version soon?

I have a few other issues, like typing and handling of removed media, will this be addressed in the release?

Thanks for your support!

**Comment by morguldir** [comment]
The plan is for a prerelease later today (in the next 24 hous)

See https://github.com/tamland/python-tidal/issues/94#issuecomment-1170568442 and https://github.com/tamland/python-tidal/issues/108#issue-1289400912 for the plans for type hints and removed media

**Comment by morguldir** [comment]
You can try it out the pre-release now https://pypi.org/project/tidalapi/0.7.0rc1/

**Comment by bennetrr** [comment]
Hmm, now I get a different error:

```python
HTTP error on 429
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\benne\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\221.5921.27\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\benne\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\221.5921.27\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/benne/projects/weckpi/weckpi-core/test_e2e/music/tidal_userpl_random.py", line 40, in <module>
    playlist = session.get_playable_data(synthpop_playlist)
  File "C:\Users\benne\projects\weckpi\weckpi-core\src\music\tidal\tidal_session.py", line 197, in get_playable_data
    output_list.append(track_to_pli(track))
  File "C:\Users\benne\projects\weckpi\weckpi-core\src\music\tidal\tidal_session.py", line 164, in track_to_playlist_item
    mrl = track.get_url()
  File "C:\Users\benne\projects\weckpi\venv\lib\site-packages\tidalapi\media.py", line 163, in get_url
    request = self.requests.request('GET', 'tracks/%s/urlpostpaywall' % self.id, params)
  File "C:\Users\benne\projects\weckpi\venv\lib\site-packages\tidalapi\request.py", line 99, in request
    request.raise_for_status()
  File "C:\Users\benne\projects\weckpi\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.tidal.com/v1/tracks/116154511/urlpostpaywall?sessionId=15fba4c2-62ee-49cc-b2f9-10a842816c21&countryCode=DE&limit=1000&urlusagemode=STREAM&audioquality=HIGH&assetpresentation=FULL
```

You can look at my code here:
- The main program that I'm using for testing is here: [bennetrr/weckpi@main/weckpi-core/test_e2e/music/tidal_userpl_random.py](https://github.com/bennetrr/weckpi/blob/main/weckpi-core/test_e2e/music/tidal_userpl_random.py)
- The code that interacts with your library is here: [bennetrr/weckpi@main/weckpi-core/src/music/tidal/](https://github.com/bennetrr/weckpi/tree/main/weckpi-core/src/music/tidal)

**Comment by bennetrr** [comment]
Makes sense. My plan was to store the URIs of the songs along with URIs from other providers in a file, and then when the user starts the music, to pass all the URLs as a list to VLC.

If I knew earlier that the URLs become invalid after a time, I would have done it directly in a different way 😆 I think, I will rewrite my music player so it manages the playlist itself.

I think, this issue can be closed now. Thanks for your help and for developing this library!
