### ISSUE TITLE
Circular import between tidalapi.media and tidalapi.session

### ISSUE THREAD

**Issue by nawordar** [tamland/python-tidal#156]
After updating to the git version of tidalapi and mopidy-tidal, I am getting the following error message:

```
lip 12 10:29:51 cezdro mopidy[1183304]: Traceback (most recent call last):
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/mopidy/__main__.py", line 129, in main
lip 12 10:29:51 cezdro mopidy[1183304]:     extension.setup(registry)
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/mopidy_tidal/__init__.py", line 37, in setup
lip 12 10:29:51 cezdro mopidy[1183304]:     from .backend import TidalBackend
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/mopidy_tidal/backend.py", line 9, in <module>
lip 12 10:29:51 cezdro mopidy[1183304]:     from tidalapi import Config, Quality, Session
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/tidalapi/__init__.py", line 4, in <module>
lip 12 10:29:51 cezdro mopidy[1183304]:     from .media import Track, Video  # noqa: F401
lip 12 10:29:51 cezdro mopidy[1183304]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/tidalapi/media.py", line 34, in <module>
lip 12 10:29:51 cezdro mopidy[1183304]:     class Media:
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/tidalapi/media.py", line 63, in Media
lip 12 10:29:51 cezdro mopidy[1183304]:     self, session: tidalapi.session.Session, media_id: Optional[str] = None
lip 12 10:29:51 cezdro mopidy[1183304]:                    ^^^^^^^^^^^^^^^^
lip 12 10:29:51 cezdro mopidy[1183304]: AttributeError: partially initialized module 'tidalapi' has no attribute 'session' (most likely due to a circular import)
```

It is caused a recent change introduced in [019ce3d](https://github.com/tamland/python-tidal/commit/019ce3d85a24d5bf8430e743d22955ca6ab76a92). After running these commands, Mopidy-Tidal runs fine:

```shell
pipx uninject mopidy tidalapi
pipx inject mopidy git+https://github.com/tamland/python-tidal.git@052e27a50d90cc51535303caf1f97db675361528
```

I originally posted this as a comment in #57, but this is a different issue.

**Comment by tehkillerbee** [comment]
Thanks, I have also added it to mopidy-tidal since the fix will most likely be needed there.

**Comment by tehkillerbee** [comment]
@nawordar Can you check if this is still an issue? I cannot replicate the bug after installing the latest tidalapi and mopidy-tidal from git.

**Comment by nawordar** [comment]
No, it is not an issue anymore, although I had to install latest tidalapi after mopidy-tidal. Otherwise, tidalapi was being overwritten with an older version.

**Comment by tehkillerbee** [comment]
Great. Yes, it will be necessary to install tidalapi manually until we update the PyPi release. 

Closing.
