### ISSUE TITLE
Don't working get_media_url

### ISSUE THREAD

**Issue by Quiec** [tamland/python-tidal#24]
Was a problem in Code.

Error:
`Traceback (most recent call last):
  File "tidal.py", line 94, in <module>
    url = session.get_media_url(track_id=track.id)
  File "/usr/local/lib/python3.6/dist-packages/tidalapi/__init__.py", line 240, in get_media_url
    r = self.request('GET', 'tracks/%s/streamUrl' % track_id, params)
  File "/usr/local/lib/python3.6/dist-packages/tidalapi/__init__.py", line 109, in request
    request.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.tidalhifi.com/v1/tracks/92309800/streamUrl?sessionId=????????-????-????-????-????????????&countryCode=IT&limit=999&soundQuality=Quality.lossless`

**Comment by morguldir** [comment]
Fixed in 54db5981c903b1521ab9f5cd0446ca868b69a6da
