### ISSUE TITLE
Cannot play track [109597132] due to missing bitDepth

### ISSUE THREAD

**Issue by GioF71** [tamland/python-tidal#241]
Hello, in order to reproduce an issue I am experiencing, I modified your pkce_login.py code.
I am directly using a track_id (track_id = "109597132" # Chris Jones - No Sanctuary Here) instead of going through the tracks of an album.
This results in an exception:

```
109597132: 'No Sanctuary Here' by 'Chris Jones'
Traceback (most recent call last):
  File "/home/power/git/audio/python-tidal/examples/pkce_login.py", line 50, in <module>
    stream = track.get_stream()
  File "/home/power/python-env/tidal-plugin-dev/lib/python3.9/site-packages/tidalapi/media.py", line 380, in get_stream
    stream = self.requests.map_json(json_obj, parse=Stream().parse)
  File "/home/power/python-env/tidal-plugin-dev/lib/python3.9/site-packages/tidalapi/request.py", line 186, in map_json
    return parse(json_obj)
  File "/home/power/python-env/tidal-plugin-dev/lib/python3.9/site-packages/tidalapi/media.py", line 423, in parse
    self.bit_depth = json_obj["bitDepth"]
KeyError: 'bitDepth'
```

Here is the code:

```
# -*- coding: utf-8 -*-

# Copyright (C) 2023- The Tidalapi Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
"""pkce_login.py: A simple example script that describes how to use PKCE login and MPEG-DASH streams"""

import tidalapi
from tidalapi import Quality
from pathlib import Path

session_file1 = Path("tidal-session-pkce.json")

session = tidalapi.Session()
# Load session from file; create a new session if necessary
session.login_session_file(session_file1, do_pkce=True)

# Override the required playback quality, if necessary
# Note: Set the quality according to your subscription.
# Low: Quality.low_96k          (m4a 96k)
# Normal: Quality.low_320k      (m4a 320k)
# HiFi: Quality.high_lossless   (FLAC)
# HiFi+ Quality.hi_res          (FLAC MQA)
# HiFi+ Quality.hi_res_lossless (FLAC HI_RES)
session.audio_quality = Quality.hi_res_lossless.value
#album_id = "77640617"    # U2 / Achtung Baby            (Max quality: HI_RES MQA, 16bit/44100Hz)
#album_id = "110827651"   # The Black Keys / Let's Rock  (Max quality: LOSSLESS FLAC, 24bit/48000Hz)
album_id = "109597127"   # Beck / Sea Change            (Max quality: HI_RES_LOSSLESS FLAC, 24bit/192000Hz)

track_id = "109597132" # Chris Jones - No Sanctuary Here
#album = session.album(album_id)
#tracks = album.tracks()
# list album tracks
#for track in tracks:
track = session.track(track_id)
if track:
    print("{}: '{}' by '{}'".format(track.id, track.name, track.artist.name))
    stream = track.get_stream()
    print("MimeType:{}".format(stream.manifest_mime_type))

    manifest = stream.get_stream_manifest()
    print("track:{}, (quality:{}, codec:{}, {}bit/{}Hz)".format(track.id,
                                                                                   stream.audio_quality,
                                                                                   manifest.get_codecs(),
                                                                                   stream.bit_depth,
                                                                                   stream.sample_rate))
    if stream.is_MPD:
        # HI_RES_LOSSLESS quality supported when using MPEG-DASH stream (PKCE only!)
        # 1. Export as MPD manifest
        mpd = stream.get_manifest_data()
        # 2. Export as HLS m3u8 playlist
        hls = manifest.get_hls()
        # with open("{}_{}.mpd".format(album_id, track.id), "w") as my_file:
        #    my_file.write(mpd)
        # with open("{}_{}.m3u8".format(album_id, track.id), "w") as my_file:
        #    my_file.write(hls)
        print(f"HLS: [{hls}]")
    elif stream.is_BTS:
        # Direct URL (m4a or flac) is available for Quality < HI_RES_LOSSLESS
        url = manifest.get_urls()
        print(f"BTS: [{url}]")
    #break

```

Thank you

**Comment by GioF71** [comment]
Code that goes through the tracks is the same as yours, just change album_id. Anyway here for completeness.
We have no error in this case

```
# -*- coding: utf-8 -*-

# Copyright (C) 2023- The Tidalapi Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
"""pkce_login.py: A simple example script that describes how to use PKCE login and MPEG-DASH streams"""

import tidalapi
from tidalapi import Quality
from pathlib import Path

session_file1 = Path("tidal-session-pkce.json")

session = tidalapi.Session()
# Load session from file; create a new session if necessary
session.login_session_file(session_file1, do_pkce=True)

# Override the required playback quality, if necessary
# Note: Set the quality according to your subscription.
# Low: Quality.low_96k          (m4a 96k)
# Normal: Quality.low_320k      (m4a 320k)
# HiFi: Quality.high_lossless   (FLAC)
# HiFi+ Quality.hi_res          (FLAC MQA)
# HiFi+ Quality.hi_res_lossless (FLAC HI_RES)
session.audio_quality = Quality.hi_res_lossless.value
#album_id = "77640617"    # U2 / Achtung Baby            (Max quality: HI_RES MQA, 16bit/44100Hz)
#album_id = "110827651"   # The Black Keys / Let's Rock  (Max quality: LOSSLESS FLAC, 24bit/48000Hz)
album_id = "109597127"   # Chris Jones Roadhouses and Automobiles standard quality

#track_id = "109597132" # Chris Jones - No Sanctuary Here
album = session.album(album_id)
tracks = album.tracks()
# list album tracks
for track in tracks:
#track = session.track(track_id)
#if track:
    print("{}: '{}' by '{}'".format(track.id, track.name, track.artist.name))
    stream = track.get_stream()
    print("MimeType:{}".format(stream.manifest_mime_type))

    manifest = stream.get_stream_manifest()
    print("track:{}, (quality:{}, codec:{}, {}bit/{}Hz)".format(track.id,
                                                                                   stream.audio_quality,
                                                                                   manifest.get_codecs(),
                                                                                   stream.bit_depth,
                                                                                   stream.sample_rate))
    if stream.is_MPD:
        # HI_RES_LOSSLESS quality supported when using MPEG-DASH stream (PKCE only!)
        # 1. Export as MPD manifest
        mpd = stream.get_manifest_data()
        # 2. Export as HLS m3u8 playlist
        hls = manifest.get_hls()
        # with open("{}_{}.mpd".format(album_id, track.id), "w") as my_file:
        #    my_file.write(mpd)
        # with open("{}_{}.m3u8".format(album_id, track.id), "w") as my_file:
        #    my_file.write(hls)
        print(f"HLS: [{hls}]")
    elif stream.is_BTS:
        # Direct URL (m4a or flac) is available for Quality < HI_RES_LOSSLESS
        url = manifest.get_urls()
        print(f"BTS: [{url}]")
    #break
```

**Comment by GioF71** [comment]
In the code from the first post, if I use a different track, e.g. 73205552, the code executes without errors.

Thank you again!

**Comment by tehkillerbee** [comment]
@GioF71 I have not yet merged the changes into master. Please test with this branch:
https://github.com/tamland/python-tidal/tree/feature/v0.7.5-prep

**Comment by GioF71** [comment]
Hello, thank you, I saw that branch after I "fixed" the issue in my branch.
I already adapted to the changes, thank you!
All the 'problematic' tracks now play properly.
