### ISSUE TITLE
[Problem] Servuce login or communication failure

### ISSUE THREAD

**Issue by TheOldPresbyope** [tamland/python-tidal#262]
I have installed python-tidal 0.7.6 in a moOde audio player 9.0.0-prerelease 6 on a Pi 5B. The underlying OS is Raspberry Pi OS Lite Bookworm. upmpdcli v1.10.14, libupnpp v0.26.4. OAUTH2 authentication credentials stored in JSON file.

Using any Control Point app and the moOde player as my UPnP Media Server, I drill down to Tidal and am presented with 7 folders: Categories, My Playlists, Playlists, My Artists, My Albums, My Tracks, Playback Statistics. Each of this folders has an image icon, all of which appear to have been retrieved from Tidal.

If I try to open the Categories folder, the Control Point app presents the error message: Service login of communication failure.

On the moOde player, the relevant journal messages are
```
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: Tidal Plugin Release 0.3.0
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: enable_read_stream_metadata=[False]
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: enable_assume_bitdepth=[True]
May 14 12:31:34 m900pre6c upmpdcli[2389]: tidal: getcachedir: me: upmpdcli
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: Cache dir for [tidal] is [/var/cache/upmpdcli/tidal]
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: DB version for [tidal] is [12]
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: browse: path: ----
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: browse: path_list: --['0$tidal$']-- last: --0$tidal$--
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: Loading credentials ...
May 14 12:31:34 m900pre6c upmpdcli[2389]: tidal: getcachedir: me: upmpdcli
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: get_credentials_from_config_or_files pkce file is not available
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: OAUTH2 Credentials provided statically
May 14 12:31:34 m900pre6c upmpdcli[2389]: tidal: getcachedir: me: upmpdcli
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: File /var/cache/upmpdcli/tidal/pkce.credentials.json not found
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: PKCE credentials not statically available
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: Credentials loaded
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: Building a new oauth2 session ...
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: Built an oauth2 session successfully, using audio_quality [LOSSLESS]
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: show_tags found handler for tag [ctgrs]: [yes]
May 14 12:31:34 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: Image for tag [ctgrs] cached [no]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: get_category_image_url category [For you] type [ItemList] cached [no]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: get_category_image_url starting load process for category [For you] type of first_item [Playlist]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: show_tags found handler for tag [myplsts]: [yes]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: Image for tag [myplsts] cached [no]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: show_tags found handler for tag [allplsts]: [yes]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: Image for tag [allplsts] cached [no]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: show_tags found handler for tag [fvrtsts]: [yes]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: Image for tag [fvrtsts] cached [no]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: show_tags found handler for tag [fvlbms]: [yes]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: Image for tag [fvlbms] cached [no]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: show_tags found handler for tag [fvrttrks]: [yes]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: Image for tag [fvrttrks] cached [no]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: show_tags found handler for tag [plbkstts]: [yes]
May 14 12:31:35 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: Image for tag [plbkstts] cached [yes]
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: browse: args: --{'cmdtalk:proc': 'browse', 'count': '20', 'offset': '0', 'flag': 'children', 'objid': '0
$tidal$/eyJuIjogInRhZyIsICJ2IjogImN0Z3JzIn0='}--
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: browse: path: --eyJuIjogInRhZyIsICJ2IjogImN0Z3JzIn0=--
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: browse: current_path [eyJuIjogInRhZyIsICJ2IjogImN0Z3JzIn0=] decodes to [{"n": "tag", "v": "ctgrs"}]
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: browse: path_list: --['0$tidal$', 'eyJuIjogInRhZyIsICJ2IjogImN0Z3JzIn0=']-- last: --eyJuIjogInRhZyIsICJ2
IjogImN0Z3JzIn0=--
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: browse: item_identifier name: --tag-- value: --ctgrs--
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: browse: should serve tag [ctgrs], handler found: [yes]
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: handler_tag_categories processing category[0]: [For you] type [ItemList]
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: get_category_image_url category [For you] type [ItemList] cached [yes]
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: handler_tag_categories processing category[1]: [From our editors] type [ItemList]
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: get_category_image_url category [From our editors] type [ItemList] cached [yes]
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: handler_tag_categories processing category[2]: [TIDAL Magazine] type [FeaturedItems]
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: get_category_image_url category [TIDAL Magazine] type [FeaturedItems] cached [no]
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: get_category_image_url category [TIDAL Magazine] (TidalFeaturedItems) first item type [EXTURL]
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: get_category_image_url category [TIDAL Magazine] (TidalFeaturedItems): not processed item EXTURL
May 14 12:33:14 m900pre6c upmpdcli[2389]: CMDTALK: tidal-app.py: processmessage: processor raised: [cannot access local variable 'image_url' where it is not associated w
ith a value]
May 14 12:33:14 m900pre6c upmpdcli[2389]: Traceback (most recent call last):
May 14 12:33:14 m900pre6c upmpdcli[2389]:   File "/usr/share/upmpdcli/cdplugins/pycommon/cmdtalk.py", line 167, in processmessage
May 14 12:33:14 m900pre6c upmpdcli[2389]:     outfields = processor.process(params)
May 14 12:33:14 m900pre6c upmpdcli[2389]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^
May 14 12:33:14 m900pre6c upmpdcli[2389]:   File "/usr/share/upmpdcli/cdplugins/pycommon/cmdtalkplugin.py", line 64, in process
May 14 12:33:14 m900pre6c upmpdcli[2389]:     return self.dispatcher.run(params[prcnmkey], params)
May 14 12:33:14 m900pre6c upmpdcli[2389]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 14 12:33:14 m900pre6c upmpdcli[2389]:   File "/usr/share/upmpdcli/cdplugins/pycommon/cmdtalkplugin.py", line 49, in run
May 14 12:33:14 m900pre6c upmpdcli[2389]:     return func(params)
May 14 12:33:14 m900pre6c upmpdcli[2389]:            ^^^^^^^^^^^^
May 14 12:33:14 m900pre6c upmpdcli[2389]:   File "/usr/share/upmpdcli/cdplugins/tidal/tidal-app.py", line 4387, in browse
May 14 12:33:14 m900pre6c upmpdcli[2389]:     entries = tag_handler(objid, item_identifier, entries)
May 14 12:33:14 m900pre6c upmpdcli[2389]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 14 12:33:14 m900pre6c upmpdcli[2389]:   File "/usr/share/upmpdcli/cdplugins/tidal/tidal-app.py", line 2403, in handler_tag_categories
May 14 12:33:14 m900pre6c upmpdcli[2389]:     entry = category_to_entry(
May 14 12:33:14 m900pre6c upmpdcli[2389]:             ^^^^^^^^^^^^^^^^^^
May 14 12:33:14 m900pre6c upmpdcli[2389]:   File "/usr/share/upmpdcli/cdplugins/tidal/tidal-app.py", line 963, in category_to_entry
May 14 12:33:14 m900pre6c upmpdcli[2389]:     category_image_url : str = get_category_image_url(
May 14 12:33:14 m900pre6c upmpdcli[2389]:                                ^^^^^^^^^^^^^^^^^^^^^^^
May 14 12:33:14 m900pre6c upmpdcli[2389]:   File "/usr/share/upmpdcli/cdplugins/tidal/tidal-app.py", line 939, in get_category_image_url
May 14 12:33:14 m900pre6c upmpdcli[2389]:     if image_url:
May 14 12:33:14 m900pre6c upmpdcli[2389]:        ^^^^^^^^^
May 14 12:33:14 m900pre6c upmpdcli[2389]: UnboundLocalError: cannot access local variable 'image_url' where it is not associated with a value
May 14 12:33:14 m900pre6c upmpdcli[1530]: :2:../src/mediaserver/cdplugins/plgwithslave.cxx:585::PlgWithSlave::browse: slave failure
```
Any thoughts on what's causing this and how I can fix it?

FYIs
-I can dive into any of the other folders, select and play tracks, although I don't understand where this particular top-level folder organization comes from or how the folders have been populated. 
-Control Point apps used include upplay on a Linux laptop, Lumin and mconnectLite on an iPad, BubbleUPnP on an Android Pixel phone.

**Comment by tehkillerbee** [comment]
Thanks for the attached issue log. Unfortunately, it looks like this issue is unrelated to tidalapi.

I would suggest creating an issue with the developer of the upmpdcli-tidal plugin.

Please see this page on details on how to create an issue/contacting the developer. 
https://www.lesbonscomptes.com/upmpdcli/pages/downloads.html

**Comment by TheOldPresbyope** [comment]
The author of the upmpdcli-tidal plugin has responded with a hotfix which works which can be found on the upmpdcli repo.
Thanks again.
