### ISSUE TITLE
getting 401 Unauthorized 

### ISSUE THREAD

**Issue by rcmpayne** [tamland/python-tidal#39]
```
pip list
tidalapi       0.6.2
```

```
C:\Users\user\Desktop>python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tidalapi
>>> session = tidalapi.Session()
>>> session.login('xxxx@xxxx.om', 'xxxxxxxxx')
{"status":401,"subStatus":6004,"userMessage":"Invalid token"}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tidalapi\__init__.py", line 83, in login
    request.raise_for_status()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username?token=kgsOxxxxxxYrNP
>>>
```

**Comment by rcmpayne** [comment]
After updating, it worked

# README - Updated 6.14.2020
# Esure you have python 3.x installed
#    1. open CMD -> python --version

# Ensure PIP is installed
#   1. Download get-pip.py @ https://bootstrap.pypa.io/
#   2. Right-Click and save file
#   3. Open CMD -> python get-pip.py
#   4. Open CMD -> pip list or pip version

# Ensure PIP is updated
#    1. OPEN CMD -> python -m pip install --upgrade pip

# Install Tidal API
#   1. Open CMD -> pip install tidalapi
#   2. Open CMD -> pip list (needs 0.6.6+)
