### ISSUE TITLE
AttributeError: 'session' 

### ISSUE THREAD

**Issue by dennisklad** [tamland/python-tidal#57]
Hi, sorry I am a newbie.

I am getting this error by executing the example code snippet.

"AttributeError: partially initialized module 'tidalapi' has no attribute 'session' (most likely due to a circular import)"
What am I doing wrong and can't import tidalapi.Session()?

**Comment by morguldir** [comment]
Can you post the exact code you are running?

**Comment by nawordar** [comment]
After updating to the git version of tidalapi and mopidy-tidal, I am running into the same problem, with the following terminal output:

```
lip 12 10:29:51 cezdro mopidy[1183304]: Traceback (most recent call last):
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/mopidy/__main__.py", line 129, in main
lip 12 10:29:51 cezdro mopidy[1183304]:     extension.setup(registry)
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/mopidy_tidal/__init__.py", line 37, in setup
lip 12 10:29:51 cezdro mopidy[1183304]:     from .backend import TidalBackend
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/mopidy_tidal/backend.py", line 9, in <module>
lip 12 10:29:51 cezdro mopidy[1183304]:     from tidalapi import Config, Quality, Session
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/tidalapi/__init__.py", line 4, in <module>
lip 12 10:29:51 cezdro mopidy[1183304]:     from .media import Track, Video  # noqa: F401
lip 12 10:29:51 cezdro mopidy[1183304]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/tidalapi/media.py", line 34, in <module>
lip 12 10:29:51 cezdro mopidy[1183304]:     class Media:
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/tidalapi/media.py", line 63, in Media
lip 12 10:29:51 cezdro mopidy[1183304]:     self, session: tidalapi.session.Session, media_id: Optional[str] = None
lip 12 10:29:51 cezdro mopidy[1183304]:                    ^^^^^^^^^^^^^^^^
lip 12 10:29:51 cezdro mopidy[1183304]: AttributeError: partially initialized module 'tidalapi' has no attribute 'session' (most likely due to a circular import)
```
It is strange how it could ever work for anyone, as there is no `from __future__ import annotations` line and `tidalapi.session` module imports `tidalapi.media` resulting in the circular import

**Comment by tehkillerbee** [comment]
> **EDIT:** It is caused a recent change introduced in [019ce3d](https://github.com/tamland/python-tidal/commit/019ce3d85a24d5bf8430e743d22955ca6ab76a92). After running the following commands, Mopidy-Tidal runs fine:

Yes, I think one of the latest changes to tidalapi broke Mopidy-Tidal. If possible, please add this as an issue there.
