### ISSUE TITLE
400 Client error when searching for track, v0.7.0

### ISSUE THREAD

**Issue by Paumanok** [tamland/python-tidal#70]
Hi, I'm attempting to write a quick script to covert a spotify playlist. I have a list of tuples consisting of [track title, artist, album]. 

Here's the snippet of code I'm running into issues with(please ignore my odd delim that gets stripped):

```
session = tidalapi.Session()

try:
    session.login_oauth()
except:
    print("Couldn't login to Tidal, here's the link")
    session.login_oauth_simple()
    exit()

for track in tracklist:
    query = ' '.join(track.split('<^>')[0:1])
    print(query)
    print(session.search(query, [tidalapi.media.Track]))
```

What I'm getting back is:

```
query text: So, I Say Goodbye...
Traceback (most recent call last):
  File "spotipy_test.py", line 34, in <module>
    print(session.search(query, [tidalapi.media.Track]))
  File "/usr/local/lib/python3.6/dist-packages/tidalapi-0.7.0-py3.6.egg/tidalapi/session.py", line 433, in search
  File "/usr/local/lib/python3.6/dist-packages/tidalapi-0.7.0-py3.6.egg/tidalapi/request.py", line 78, in request
  File "/home/sawyer/.local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.tidal.com/v1/search?limit=50&query=So%2C+I+Say+Goodbye...&offset=0&types=tracks`
```

I'm not sure if this is an issue with my input data or an issue with the api endpoint. I adjusted the code to continue on failure and none of the 200 tracks passed. 

I understand 0.7.x is still WIP so I apologize if this is known.

**Comment by morguldir** [comment]
I can't reproduce, can you enable debugging?

```python
logging.basicConfig(level=logging.DEBUG)
```

**Comment by Paumanok** [comment]
Here's the output with logging. At the end I manually killed it.

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): auth.tidal.com:443
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/device_authorization HTTP/1.1" 200 None
So, I Say Goodbye...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.tidal.com:443
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/token HTTP/1.1" 400 None
DEBUG:urllib3.connectionpool:https://api.tidal.com:443 "GET /v1/search?limit=50&query=So%2C+I+Say+Goodbye...&offset=0&types=artists%2Calbums%2Ctracks%2Cvideos%2Cplaylists HTTP/1.1" 400 77
DEBUG:tidalapi.request:request: https://api.tidal.com/v1/search?limit=50&query=So%2C+I+Say+Goodbye...&offset=0&types=artists%2Calbums%2Ctracks%2Cvideos%2Cplaylists
Traceback (most recent call last):
  File "spotipy_test.py", line 33, in <module>
    print(session.search(query))
  File "/usr/local/lib/python3.6/dist-packages/tidalapi-0.7.0-py3.6.egg/tidalapi/session.py", line 433, in search
  File "/usr/local/lib/python3.6/dist-packages/tidalapi-0.7.0-py3.6.egg/tidalapi/request.py", line 78, in request
  File "/home/sawyer/.local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.tidal.com/v1/search?limit=50&query=So%2C+I+Say+Goodbye...&offset=0&types=artists%2Calbums%2Ctracks%2Cvideos%2Cplaylists
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/token HTTP/1.1" 400 None
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/token HTTP/1.1" 400 None
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/token HTTP/1.1" 400 None
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/token HTTP/1.1" 400 None
DEBUG:urllib3.connectionpool:https://auth.tidal.com:443 "POST /v1/oauth2/token HTTP/1.1" 400 None
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by Paumanok** [comment]
I took the generated request and pasted it into a browser to see what it returned. The API page returned a user message "missing country code".

Upon fixing that in my code, the browser gives a "missing token"

So I changed my code to use login_oauth_simple() and it began working.

When session.login_oauth() didn't fail, I assumed login was a success.
