### ISSUE TITLE
404 Client Error on example code 0.7.x

### ISSUE THREAD

**Issue by ZorvShadow** [tamland/python-tidal#87]
After copying and pasting the example code on python IDLE 3.9 and following the steps to login on the browser I get the following error:
```
====================== RESTART: C:\Users\si\Downloads\a.py =====================
Visit link.tidal.com/PEJYC to log in, the code will expire in 300 seconds
Traceback (most recent call last):
  File "C:\Users\si\Downloads\a.py", line 6, in <module>
    album = session.album(16909093)
  File "C:\Users\si\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tidalapi\session.py", line 562, in album
    return tidalapi.Album(session=self, album_id=album_id)
  File "C:\Users\si\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tidalapi\album.py", line 59, in __init__
    self.requests.map_request('albums/%s' % album_id, parse=self.parse)
  File "C:\Users\si\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tidalapi\request.py", line 104, in map_request
    json_obj = self.request('GET', url, params).json()
  File "C:\Users\si\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tidalapi\request.py", line 87, in request
    request.raise_for_status()
  File "C:\Users\si\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.tidal.com/v1/albums/16909093?sessionId=ee202503-d785-4d43-96a4-130fc7192256&countryCode=MX&limit=1000
```

**Comment by divadsn** [comment]
Because that album does not exist in your region or got removed by the artist?

**Comment by ZorvShadow** [comment]
> Because that album does not exist in your region or got removed by the artist, it's a 404 Not Found error?

I'm so stupid thank you so much
