### ISSUE TITLE
Public

### ISSUE THREAD

**Issue by Momce123123** [tamland/python-tidal#92]
{"status":401,"subStatus":6004,"userMessage":"Invalid token"}
Traceback (most recent call last):
  File "<console>", line 0, in <module>
  File "D:\develop\Python\lib\site-packages\tidalapi\__init__.py", line 83, in login
    request.raise_for_status()
  File "D:\develop\Python\lib\site-packages\requests\models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username?token=kgsOOmYk3zShYrNP

**Comment by Momce123123** [comment]
> {"status":401,"subStatus":6004,"userMessage":"Invalid token"}
> Traceback (most recent call last):
> File "", line 0, in 
> File "D:\develop\Python\lib\site-packages\tidalapi__init__.py", line 83, in login
> request.raise_for_status()
> File "D:\develop\Python\lib\site-packages\requests\models.py", line 893, in raise_for_status
> raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username?token=kgsOOmYk3zShYrNP
