### ISSUE TITLE
Removed content is not handled correctly and results in HTTPError

### ISSUE THREAD

**Issue by tehkillerbee** [tamland/python-tidal#94]
When browsing albums, removed content will result in HTTPError. 
Maybe there is a better way to determine if an URI contains content available for playback?

```
Jan 30 12:56:24 T430 mopidy[8919]: ERROR    [Core-7] mopidy.core.library TidalBackend backend caused an exception.
Jan 30 12:56:24 T430 mopidy[8919]: Traceback (most recent call last):
Jan 30 12:56:24 T430 mopidy[8919]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
Jan 30 12:56:24 T430 mopidy[8919]:     yield
Jan 30 12:56:24 T430 mopidy[8919]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 181, in get_images
Jan 30 12:56:24 T430 mopidy[8919]:     if future.get() is None:
Jan 30 12:56:24 T430 mopidy[8919]:   File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
Jan 30 12:56:24 T430 mopidy[8919]:     _compat.reraise(*self._data['exc_info'])
Jan 30 12:56:24 T430 mopidy[8919]:   File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
Jan 30 12:56:24 T430 mopidy[8919]:     raise value
Jan 30 12:56:24 T430 mopidy[8919]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
Jan 30 12:56:24 T430 mopidy[8919]:     response = self._handle_receive(envelope.message)
Jan 30 12:56:24 T430 mopidy[8919]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
Jan 30 12:56:24 T430 mopidy[8919]:     return callee(*message.args, **message.kwargs)
Jan 30 12:56:24 T430 mopidy[8919]:   File "/usr/local/lib/python3.8/dist-packages/Mopidy_Tidal-0.2.7-py3.8.egg/mopidy_tidal/library.py", line 180, in get_images
Jan 30 12:56:24 T430 mopidy[8919]:     album = session.get_album(album_id)
Jan 30 12:56:24 T430 mopidy[8919]:   File "/usr/local/lib/python3.8/dist-packages/tidalapi-0.6.9-py3.8.egg/tidalapi/__init__.py", line 362, in get_album
Jan 30 12:56:24 T430 mopidy[8919]:     return self._map_request('albums/%s' % album_id, ret='album')
Jan 30 12:56:24 T430 mopidy[8919]:   File "/usr/local/lib/python3.8/dist-packages/tidalapi-0.6.9-py3.8.egg/tidalapi/__init__.py", line 432, in _map_request
Jan 30 12:56:24 T430 mopidy[8919]:     json_obj = self.request('GET', url, params).json()
Jan 30 12:56:24 T430 mopidy[8919]:   File "/usr/local/lib/python3.8/dist-packages/tidalapi-0.6.9-py3.8.egg/tidalapi/__init__.py", line 338, in request
Jan 30 12:56:24 T430 mopidy[8919]:     request.raise_for_status()
Jan 30 12:56:24 T430 mopidy[8919]:   File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
Jan 30 12:56:24 T430 mopidy[8919]:     raise HTTPError(http_error_msg, response=self)
Jan 30 12:56:24 T430 mopidy[8919]: requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.tidalhifi.com/v1/albums/38264741?sessionId=<sessionID>&countryCode=DK&limit=999
```

The album in question (38264741) correspond to Attach & Release by The Black Keys. I assume it has been removed at some point after I added it to my albums.

**Comment by morguldir** [comment]
You opened this for 0.6.x i guess, but in 0.7.x albums and media have the available field, is that good enough? Because returning 404 when it actually doesn't exist seems okay to me, at least if you can check first.

@bennetrr thoughts?
